services:
  - type: web
    name: truckplan
    env: python
    plan: free
    rootDir: ./truck
    buildCommand: bash build.sh
    startCommand: gunicorn truck.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: RENDER
        value: "True"

