# Generated by Django 5.2.5 on 2025-09-17 17:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('combustivel', 'Combustível'), ('manutencao', 'Manutenção'), ('pecas', 'Peças'), ('seguro', 'Seguro'), ('documentacao', 'Documentação'), ('multas', 'Multas'), ('estacionamento', 'Estacionamento'), ('pedagio', 'Pedágio'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Gasto')),
                ('data', models.DateField(verbose_name='Data')),
                ('veiculo_placa', models.CharField(max_length=20, verbose_name='Placa do Veículo')),
                ('km_atual', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Atual')),
                ('oficina_fornecedor', models.CharField(max_length=200, verbose_name='Oficina/Fornecedor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('forma_pagamento', models.CharField(choices=[('vista', 'À Vista'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('parcelado', 'Parcelado')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status_pagamento', models.CharField(choices=[('pago', 'Pago'), ('nao_pago', 'Não Pago'), ('parcial', 'Parcialmente Pago')], max_length=20, verbose_name='Status do Pagamento')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Custo Geral',
                'verbose_name_plural': 'Custos Gerais',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('partida', models.CharField(max_length=200, verbose_name='Local de Partida')),
                ('chegada', models.CharField(max_length=200, verbose_name='Local de Chegada')),
                ('diarias', models.PositiveIntegerField(verbose_name='Número de Diárias')),
                ('valor_diarias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor das Diárias')),
                ('litros_gasolina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Litros de Gasolina')),
                ('gasto_gasolina', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gasto com Gasolina')),
                ('receita_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Receita do Frete')),
                ('motorista', models.CharField(max_length=100, verbose_name='Motorista')),
                ('caminhao', models.CharField(max_length=50, verbose_name='Caminhão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Relatório Diário',
                'verbose_name_plural': 'Relatórios Diários',
                'ordering': ['-data_viagem', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_mes', models.CharField(max_length=7, unique=True, verbose_name='Ano-Mês (YYYY-MM)')),
                ('pecas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Peças')),
                ('seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Seguro')),
                ('manutencao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Manutenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Custo Mensal',
                'verbose_name_plural': 'Custos Mensais',
                'ordering': ['-ano_mes'],
            },
        ),
        migrations.CreateModel(
            name='MotoristaSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=100, verbose_name='Motorista')),
                ('ano_mes', models.CharField(max_length=7, verbose_name='Ano-Mês (YYYY-MM)')),
                ('salario_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salário Base')),
                ('bonus_viagens', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bônus por Viagens')),
                ('desconto_faltas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto por Faltas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Salário do Motorista',
                'verbose_name_plural': 'Salários dos Motoristas',
                'ordering': ['-ano_mes', 'motorista'],
                'unique_together': {('motorista', 'ano_mes')},
            },
        ),
    ]
