# Generated by Django 5.2.5 on 2025-09-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_custosgerais_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('tipo_custo', models.CharField(choices=[('parcela_caminhao', 'Parcela do Caminhão'), ('seguro', 'Seguro'), ('ipva', 'IPVA'), ('licenciamento', 'Licenciamento'), ('manutencao_preventiva', 'Manutenção Preventiva'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Custo')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Custo Fixo Mensal',
                'verbose_name_plural': 'Custos Fixos Mensais',
                'ordering': ['-data_inicio', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status_pagamento', models.CharField(choices=[('pago', 'Pago'), ('nao_pago', 'Não Pago'), ('parcial', 'Parcialmente Pago')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('custo_geral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='login.custosgerais', verbose_name='Custo Geral')),
            ],
            options={
                'verbose_name': 'Parcela de Custo',
                'verbose_name_plural': 'Parcelas de Custos',
                'ordering': ['custo_geral', 'numero_parcela'],
            },
        ),
    ]
