# Generated by Django 5.2.5 on 2025-09-18 18:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_custofixomensal_parcelacusto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custosgerais',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor'),
        ),
    ]
