# Generated by Django 4.2.7 on 2025-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_custosgerais_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custofixomensal',
            name='tipo_custo',
            field=models.CharField(choices=[('seguro', 'Seguro'), ('ipva', 'IPVA'), ('licenciamento', 'Licenciamento'), ('manutencao_preventiva', 'Manutenção Preventiva'), ('outros', 'Outros')], max_length=30, verbose_name='Tipo de Custo'),
        ),
        migrations.AlterField(
            model_name='custosgerais',
            name='forma_pagamento',
            field=models.CharField(choices=[('vista', 'À Vista'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'PIX'), ('transferencia', 'Transferência'), ('cheque', 'Cheque')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.DeleteModel(
            name='ParcelaCusto',
        ),
    ]
